/**
 * Pure renderers for the generated environment artifacts. Kept dependency-
 * and side-effect-free (no file I/O) so they're deterministically testable;
 * `scripts/generate-env-docs.ts` is the thin CLI that reads/writes files.
 */
import {
  ENV_SCHEMA,
  ENV_VAR_GROUPS,
  ENV_VAR_GROUP_ORDER,
  envVarsByGroup,
  type EnvVarDefinition,
} from "@/lib/envSchema";

const GENERATED_FILE_NOTICE =
  "Generated by `npm run env:generate` from lib/envSchema.ts. Do not hand-edit; run `npm run env:check` in CI to catch drift.";

function commentLines(entry: EnvVarDefinition): string[] {
  return (entry.notes && entry.notes.length > 0
    ? entry.notes
    : [entry.summary]
  ).map((line) => `# ${line}`);
}

/** Renders the full `.env.example` contents from the schema. */
export function renderEnvExample(): string {
  const sections: string[] = [];
  for (const group of ENV_VAR_GROUP_ORDER) {
    const vars = envVarsByGroup(group);
    if (vars.length === 0) continue;
    const heading = ENV_VAR_GROUPS[group].heading;
    const dashes = "─".repeat(Math.max(3, 66 - heading.length));
    const lines = [`# ── ${heading} ${dashes}`];
    vars.forEach((entry, index) => {
      lines.push(...commentLines(entry));
      lines.push(`${entry.key}="${entry.defaultValue}"`);
      if (index < vars.length - 1) lines.push("");
    });
    sections.push(lines.join("\n"));
  }
  return `${sections.join("\n\n")}\n`;
}

/** Renders a human-readable, secret-free environment reference doc. */
export function renderEnvDocs(): string {
  const lines: string[] = [
    "# Environment variables",
    "",
    `<!-- ${GENERATED_FILE_NOTICE} -->`,
    "",
    "Every variable this app reads, grouped the same way as `.env.example`.",
    "Secret values are never included here or in any generated artifact —",
    "only names, defaults, and descriptions.",
    "",
  ];
  for (const group of ENV_VAR_GROUP_ORDER) {
    const vars = envVarsByGroup(group);
    if (vars.length === 0) continue;
    const info = ENV_VAR_GROUPS[group];
    lines.push(`## ${info.heading}`, "");
    lines.push(`_${info.kind === "core" ? "Core" : "Optional integration"}._`, "");
    lines.push("| Variable | Secret | Description |", "|---|---|---|");
    for (const entry of vars) {
      lines.push(
        `| \`${entry.key}\` | ${entry.secret ? "yes" : "no"} | ${entry.summary} |`,
      );
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

export { ENV_SCHEMA };
